[package]
name = "carnival"
version = "0.1.0"
description = "an experimental Nostr client"
license = "MIT"
default-run = "carnival"
edition = "2021"

[dependencies]
vgtk = "0.3.0"
pretty_env_logger = "0.4"
async-tungstenite = { version = "*", features = ["gio-runtime"] }
futures = "0.3"
